version: '3'

services:
  Oswalds-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  # service1:
  #   build: ./service1
  #   depends_on:
  #     - Oswalds-db

  # service2:
  #   build: ./service2
  #   depends_on:
  #     - Oswalds-db
